load("@aspect_rules_js//js:defs.bzl", "js_binary")
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@npm//:defs.bzl", "npm_link_all_packages")

npm_link_all_packages(name = "node_modules")

js_binary(
    name = "tsc",
    data = ["@npm_typescript//:node_modules/typescript"],
    entry_point = "@npm_typescript//:tsc_entrypoint",
    patch_node_fs = False,
)

ts_project(
    name = "ts",
    srcs = ["index.ts"],
    deps = [
        ":node_modules/lib",
    ],
    tsc = ":tsc",
    tsconfig = {
    },
)
